name: Publish to npm registries

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@keenthemes'

      - name: Install dependencies
        run: npm install

      - name: Build lib
        run: npm run build:lib

      - name: Build css
        run: npm run build:css

      - name: Build package
        run: npm run build:prod

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js for npmjs.org
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Publish to npmjs.org
        run: npm publish --registry https://registry.npmjs.org/ --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}